import Landing from "./pages/Landing"
import Proyectos from "./pages/Proyectos"
import Swatches from "./pages/Swatches"
import Marketplace from "./pages/Marketplace"
import Perfil from "./pages/Perfil"

const routes = [
    {
        id : 1,
        htmlId : "page-landing",
        path : "/",
        isInit : false,
        exact : true,
        Element : Landing,
        isPrivate : false,
        isHeaderLink : false,
        linkOrder : 1,
        isHashLink : false,
        linkText : "Inicio",
        isRoute : true,
        privileges : ["admin", "user"]
    },
    {
        id : 2,
        htmlId : "swatches",
        path : "/swatches",
        isInit : true,
        exact : true,
        Element : Swatches,
        isPrivate : false,
        isHeaderLink : false,
        linkOrder : 6,
        isHashLink : false,
        linkText : "Swatches",
        isRoute : true,
        privileges : ["admin", "user"]
    },
    {
        id : 3,
        htmlId : "proyectos",
        path : "/proyectos",
        isInit : false,
        exact : true,
        Element : Proyectos,
        isPrivate : false,
        isHeaderLink : true,
        linkOrder : 3,
        isHashLink : false,
        linkText : "Proyectos",
        isRoute : true,
        privileges : ["admin", "user"]
    },
    {
        id : 4,
        htmlId : "marketplace",
        path : "/marketplace",
        isInit : false,
        exact : true,
        Element : Marketplace,
        isPrivate : false,
        isHeaderLink : true,
        linkOrder : 4,
        isHashLink : false,
        linkText : "Marketplace",
        isRoute : true,
        privileges : ["admin", "user"]
    },
    {
        id : 5,
        htmlId : "perfil",
        path : "/perfil",
        isInit : false,
        exact : true,
        Element : Perfil,
        isPrivate : true,
        isHeaderLink : true,
        linkOrder : 8,
        isHashLink : false,
        linkText : "Perfil",
        isRoute : true,
        privileges : ["admin", "user"]
    },
    {
        id : 6,
        htmlId : "que-es-tokenizacion",
        path : "/que-es-tokenizacion",
        isInit : true,
        hash : "/#que-es-tokenizacion",
        exact : true,
        Element : () => <h1>Que es la tokenización?</h1>,
        isPrivate : false,
        isHeaderLink : true,
        linkOrder : 1,
        isHashLink : true,
        linkText : "Que es la tokenización?",
        isRoute : false,
        privileges : ["admin", "user"]
    },
    {
        id : 7,
        htmlId : "beneficios",
        path : "/beneficios",
        isInit : true,
        hash : "/#beneficios",
        exact : true,
        Element : () => <h1>Beneficios</h1>,
        isPrivate : false,
        isHeaderLink : true,
        linkOrder : 2,
        isHashLink : true,
        linkText : "Beneficios",
        isRoute : false,
        privileges : ["admin", "user"]
    },
    {
        id : 8,
        htmlId : "tokenizar",
        path : "/tokenizar",
        isInit : false,
        hash : "/#tokenizar",
        exact : true,
        Element : () => <h1>Tokenizar</h1>,
        isPrivate : true,
        isHeaderLink : true,
        linkOrder : 5,
        isHashLink : false,
        linkText : "Tokenizar",
        isRoute : true,
        privileges : ["admin"]
    },
    {
        id : 9,
        htmlId : "dividendos",
        path : "/dividendos",
        isInit : false,
        hash : "/#dividendos",
        exact : true,
        Element : () => <h1>Dividendos</h1>,
        isPrivate : true,
        isHeaderLink : true,
        linkOrder : 7,
        isHashLink : false,
        linkText : "Repartir Dividendos",
        isRoute : true,
        privileges : ["admin"]
    },
    {
        id : 10,
        htmlId : "registro",
        path : "/registro",
        isInit : false,
        hash : "/#registro",
        exact : true,
        Element : () => <h1>Registro</h1>,
        isPrivate : false,
        isHeaderLink : false,
        linkOrder : 1,
        isHashLink : false,
        linkText : "Registro",
        isRoute : true,
        privileges : ["admin", "user"]
    }
]

export default routes